CREATE TABLE PERSONAS(
    PERSONA_NOMBRE VARCHAR(250),
    PERSONA_PRECEDENCIA VARCHAR(250),
    PERSONA_FECHA_HORA_INGRESO VARCHAR(20),
    PERSONA_FECHA_HORA_SALIDA VARCHAR(20),
    PERSONA_RAZON_INGRESO VARCHAR(250)
);